name: 'is-my-node-vulnerable'
description: 'checks if your Node.js installation is vulnerable to known security vulnerabilities'
author: 'RafaelGSS'

runs:
  using: 'node16'
  main: 'dist/index.js'

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'flag'
  color: 'red'