name: 'is-my-node-vulnerable'
description: 'checks if your Node.js installation is vulnerable to known security vulnerabilities'
author: 'RafaelGSS'

runs:
  using: 'node18'
  main: 'dist/index.js'

inputs:
  node-version:
    description: 'Node.js version to check'
    required: true
    default: '16.13.0'
  platform:
    description: 'Platform to check'
    required: false

# https://actions-cool.github.io/github-action-branding/
branding:
  icon: 'flag'
  color: 'red'