name: Test

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 21, 22, 23]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install
        run: |
          npm install

      - name: Run validator
        run: |
          npm run test

      - name: Ensure Build
        run: |
          npm run build

  old-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [0.12, 4, 6, 8, 9, 10, 12]

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Run test
        run: |
          node setup-test.js
